apiVersion: v1
kind: Namespace
metadata:
  name: lab-test-jbs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-test-jbs
  namespace: lab-test-jbs
  labels:
    app: backend-nest-test-jbs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-test-jbs
  template:
    metadata:
      labels:
        app: backend-nest-test-jbs
    spec:
      containers:
      - name: backend-nest-test-jbs
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-nest-test-jbs
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nest-svc
  namespace: lab-test-jbs
  labels:
    app: backend-nest-svc
spec:
  selector:
     app: backend-nest-test-jbs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend-nest-test-jbs
  namespace: lab-test-jbs
spec:
  ingressClassName: nginx
  rules:
  - host: jbs.devops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-nest-test-jbs-svc
            port:
              number: 80
